### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual#12]
This issue was created, based on feedback from the community.

People find it disturbing to click multiple times on "next" to find the basic information inside an extension manual. We should think about changing the example manual to change this.

The "What does it do" should be on the first page. The TOC should not be rendered at all, as this duplicates the TOC in the sidebar.

Also Versions and further detail information might be placed in an appendix. The version is already rendered in the top left corner on each page, same goes for the extension name.

Related:

* [Define general structure of a manual](https://github.com/TYPO3-Documentation/T3DocTeam/issues/6)
* [Optimize start page of manuals](https://github.com/TYPO3-Documentation/T3DocTeam/issues/89)

**Comment by sypets** [comment]
@DanielSiepmann Thanks for collecting and documenting this feedback. 

btw, you are currently not watching this repo. I was not watching it either. That is why I missed this issue.

A similar issue was raised at the DevDays last year: 

* There is often no information on the start page what it's about and you have to click three times (through sitemap) to got to third page to find out what extension is about. Is this what you mean?

3 Things: I am already working on this

* I made several changes to this extension manual already. Some of my changes had gone missing but were restored. Also, currently rendered manual is not up to date: source in repo is newer than rendered version (see https://github.com/TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual/blob/master/Documentation/Index.rst). I will look into it
* I already made some changes due to this to other manuals.
* I am creating documentation and templates for this in general. I think we should have an updated sample start page. It is the same for extension manuals / guides / tutorials

I already started to change these things in other manuals.

What I commonly do now:

* add link to sitemap instead of toctree on start page. Put sitemap at the end
* add **About this manual** on start page
* have short information for contributors on start page
* remove "rendered" date / time because that is already on footer

See [Getting started](https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/)
